name: ci-guessing_game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check guessing_game
      run: cd guessing_game && cargo check
    - name: build guessing_game
      run: cd guessing_game && cargo build --verbose
    - name: run guessing_game tests
      run: cd guessing_game && cargo test --verbose
