name: ci-prototype

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check
      run: cd prototype/api && cargo check
    - name: build
      run: cd prototype/api && cargo build
    - name: test
      run: cd prototype/api && cargo test
