name: ci-rest-api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check rest-api
      run: cd rest-api && cargo check
    - name: build rest-api
      run: cd rest-api && cargo build --verbose
    - name: run rest-api tests
      run: cd rest-api && cargo test --verbose
